/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

/**
 *
 * @author caoimhemalone
 */
public class HelloWorld extends javax.swing.JFrame {

    /**
     * Creates new form HelloWorld
     */
    public HelloWorld() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question Applicaion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(139, 18, 128, 16);

        jLabel2.setText("Question type:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 64, 92, 16);

        jRadioButton1.setText("Basic Question");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(6, 98, 125, 23);

        jRadioButton2.setText("MultiChoice Question");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(207, 98, 168, 23);

        jRadioButton3.setText("Essay Question");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(6, 139, 128, 23);

        jRadioButton4.setText("Picture Question");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(207, 139, 136, 23);

        jLabel3.setText("Question Text");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(55, 197, 89, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(175, 191, 147, 28);

        jLabel4.setText("Correct Answer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 245, 96, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(175, 239, 147, 28);

        jLabel5.setText("Mark");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(55, 291, 31, 16);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(175, 285, 147, 28);

        jButton1.setText("Add Question");
        getContentPane().add(jButton1);
        jButton1.setBounds(21, 350, 130, 29);

        jButton2.setText("Clear Form");
        getContentPane().add(jButton2);
        jButton2.setBounds(197, 350, 112, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myproject/Background.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-5, 0, 420, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelloWorld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
