/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author caoimhemalone
 */
public class lcPhy extends javax.swing.JFrame {

    /**
     * Creates new form lcPhy
     */
    public lcPhy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCPhyLbl = new javax.swing.JLabel();
        modDesBtn = new javax.swing.JButton();
        markSchBtn = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();
        expBtn = new javax.swing.JButton();
        homelcPhy = new javax.swing.JButton();
        backlcPhy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(273, 398));

        lCPhyLbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lCPhyLbl.setText("Leaving Cert Physics ");

        modDesBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        modDesBtn.setText("Module Description");
        modDesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDesBtnActionPerformed(evt);
            }
        });

        markSchBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        markSchBtn.setText("Marking Scheme");
        markSchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markSchBtnActionPerformed(evt);
            }
        });

        quizBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        quizBtn.setText("Quiz");
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });

        expBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        expBtn.setText("Experiments");
        expBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expBtnActionPerformed(evt);
            }
        });

        homelcPhy.setText("Home");
        homelcPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homelcPhyActionPerformed(evt);
            }
        });

        backlcPhy.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        backlcPhy.setText("Back");
        backlcPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backlcPhyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(markSchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modDesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCPhyLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backlcPhy))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homelcPhy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homelcPhy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lCPhyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modDesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(markSchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(quizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(expBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(backlcPhy)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homelcPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homelcPhyActionPerformed
        // TODO add your handling code here:
        new GUI().setVisible(true);
    }//GEN-LAST:event_homelcPhyActionPerformed

    private void backlcPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backlcPhyActionPerformed
        // TODO add your handling code here:
        new Level().setVisible(true);
    }//GEN-LAST:event_backlcPhyActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        // TODO add your handling code here:
        new Quiz().setVisible(true);
    }//GEN-LAST:event_quizBtnActionPerformed

    private void modDesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDesBtnActionPerformed
        // TODO add your handling code here:
        new ModuleDescriptorPhy().setVisible(true);
    }//GEN-LAST:event_modDesBtnActionPerformed

    private void markSchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markSchBtnActionPerformed
        // TODO add your handling code here:
        new MarkingSchemePhy().setVisible(true);
    }//GEN-LAST:event_markSchBtnActionPerformed

    private void expBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expBtnActionPerformed
        // TODO add your handling code here:
        new ExperimentsPhy().setVisible(true);
    }//GEN-LAST:event_expBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lcPhy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lcPhy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lcPhy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lcPhy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lcPhy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backlcPhy;
    private javax.swing.JButton expBtn;
    private javax.swing.JButton homelcPhy;
    private javax.swing.JLabel lCPhyLbl;
    private javax.swing.JButton markSchBtn;
    private javax.swing.JButton modDesBtn;
    private javax.swing.JButton quizBtn;
    // End of variables declaration//GEN-END:variables
}
