/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author caoimhemalone
 */
public class Level extends javax.swing.JFrame {

    /**
     * Creates new form Level
     */
    public Level() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelLbl = new javax.swing.JLabel();
        ordinaryLbl = new javax.swing.JButton();
        higherLbl = new javax.swing.JButton();
        homeLevel = new javax.swing.JButton();
        backLevel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(273, 397));

        levelLbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        levelLbl.setText("Level");

        ordinaryLbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        ordinaryLbl.setText("Ordinary");
        ordinaryLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordinaryLblActionPerformed(evt);
            }
        });

        higherLbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        higherLbl.setText("Higher");
        higherLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherLblActionPerformed(evt);
            }
        });

        homeLevel.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        homeLevel.setText("Home");
        homeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLevelActionPerformed(evt);
            }
        });

        backLevel.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        backLevel.setText("Back");
        backLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLevelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(higherLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ordinaryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(levelLbl)
                                .addGap(97, 97, 97))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backLevel)
                            .addComponent(homeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levelLbl)
                    .addComponent(homeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(ordinaryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(higherLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(backLevel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordinaryLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordinaryLblActionPerformed
        // TODO add your handling code here:
        new lcPhy().setVisible(true);
    }//GEN-LAST:event_ordinaryLblActionPerformed

    private void higherLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherLblActionPerformed
        // TODO add your handling code here:
        new lcPhy().setVisible(true);
    }//GEN-LAST:event_higherLblActionPerformed

    private void homeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLevelActionPerformed
        // TODO add your handling code here:
        new GUI().setVisible(true);
    }//GEN-LAST:event_homeLevelActionPerformed

    private void backLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLevelActionPerformed
        // TODO add your handling code here:
        new GUI().setVisible(true);
    }//GEN-LAST:event_backLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLevel;
    private javax.swing.JButton higherLbl;
    private javax.swing.JButton homeLevel;
    private javax.swing.JLabel levelLbl;
    private javax.swing.JButton ordinaryLbl;
    // End of variables declaration//GEN-END:variables
}
