/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Logger;

/**
 *
 * @author caoimhemalone
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        quizLbl = new javax.swing.JLabel();
        bQQ1Lbl = new javax.swing.JLabel();
        bQQ1TF = new javax.swing.JTextField();
        bQQ2Lbl = new javax.swing.JLabel();
        bQQ2TF = new javax.swing.JTextField();
        bQQ3Lbl = new javax.swing.JLabel();
        bQQ3TF = new javax.swing.JTextField();
        pic1 = new javax.swing.JPanel();
        pic2 = new javax.swing.JPanel();
        pic3 = new javax.swing.JPanel();
        pic4 = new javax.swing.JPanel();
        PicQueLbl = new javax.swing.JLabel();
        pQQ1Lbl = new javax.swing.JLabel();
        pQQ1TF = new javax.swing.JTextField();
        pQQ2Lbl = new javax.swing.JLabel();
        pQQ2TF = new javax.swing.JTextField();
        pQQ3Lbl = new javax.swing.JLabel();
        pQQ3TF = new javax.swing.JTextField();
        basicQuestionLbl = new javax.swing.JLabel();
        multipleChoiceLbl = new javax.swing.JLabel();
        mCQ1Lbl = new javax.swing.JLabel();
        answer1Btn = new javax.swing.JRadioButton();
        answer3Btn = new javax.swing.JRadioButton();
        answer4Btn = new javax.swing.JRadioButton();
        answer2Btn = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        homeQuiz = new javax.swing.JButton();
        backQuiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(273, 397));
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(259, 398));

        quizLbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        quizLbl.setText("Quiz");

        bQQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bQQ1Lbl.setText("Question 1:");

        bQQ2Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bQQ2Lbl.setText("Question 2:");

        bQQ3Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bQQ3Lbl.setText("Question 3:");

        bQQ3TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQQ3TFActionPerformed(evt);
            }
        });

        pic1.setBackground(new java.awt.Color(204, 0, 204));
        pic1.setForeground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout pic1Layout = new javax.swing.GroupLayout(pic1);
        pic1.setLayout(pic1Layout);
        pic1Layout.setHorizontalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pic1Layout.setVerticalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pic2.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout pic2Layout = new javax.swing.GroupLayout(pic2);
        pic2.setLayout(pic2Layout);
        pic2Layout.setHorizontalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pic2Layout.setVerticalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pic3.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout pic3Layout = new javax.swing.GroupLayout(pic3);
        pic3.setLayout(pic3Layout);
        pic3Layout.setHorizontalGroup(
            pic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pic3Layout.setVerticalGroup(
            pic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pic4.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout pic4Layout = new javax.swing.GroupLayout(pic4);
        pic4.setLayout(pic4Layout);
        pic4Layout.setHorizontalGroup(
            pic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pic4Layout.setVerticalGroup(
            pic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PicQueLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        PicQueLbl.setText("Picture Question");

        pQQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        pQQ1Lbl.setText("Question 1:");

        pQQ2Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        pQQ2Lbl.setText("Question 2:");

        pQQ3Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        pQQ3Lbl.setText("Question 3:");

        basicQuestionLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        basicQuestionLbl.setText("Basic Question");

        multipleChoiceLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        multipleChoiceLbl.setText("Mulitiple Choice");

        mCQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        mCQ1Lbl.setText("Question 1:");

        answer1Btn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        answer1Btn.setText("Answer 1");
        answer1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1BtnActionPerformed(evt);
            }
        });

        answer3Btn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        answer3Btn.setText("Answer 3");
        answer3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3BtnActionPerformed(evt);
            }
        });

        answer4Btn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        answer4Btn.setText("Answer 4");
        answer4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4BtnActionPerformed(evt);
            }
        });

        answer2Btn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        answer2Btn.setText("Answer 2");
        answer2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2BtnActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        resetBtn.setText("Reset");

        homeQuiz.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        homeQuiz.setText("Home");
        homeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeQuizActionPerformed(evt);
            }
        });

        backQuiz.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        backQuiz.setText("Back");
        backQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(answer3Btn)
                                    .addComponent(answer1Btn)
                                    .addComponent(submitBtn))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answer2Btn)
                                    .addComponent(answer4Btn)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pic4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pQQ1Lbl)
                                    .addComponent(pQQ2Lbl)
                                    .addComponent(pQQ3Lbl))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pQQ3TF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pQQ2TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(pQQ1TF)))
                            .addComponent(mCQ1Lbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(multipleChoiceLbl))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bQQ1Lbl)
                                            .addComponent(bQQ2Lbl)
                                            .addComponent(bQQ3Lbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(basicQuestionLbl))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(quizLbl)
                                .addGap(18, 18, 18)
                                .addComponent(backQuiz))))
                    .addComponent(homeQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(PicQueLbl)))
                .addGap(22, 45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(quizLbl))
                            .addComponent(homeQuiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(basicQuestionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bQQ1Lbl)
                            .addComponent(bQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bQQ2Lbl)
                            .addComponent(bQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bQQ3Lbl)
                            .addComponent(bQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(PicQueLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backQuiz)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pQQ1Lbl)
                    .addComponent(pQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pQQ2Lbl)
                    .addComponent(pQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pQQ3Lbl)
                    .addComponent(pQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(multipleChoiceLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mCQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer1Btn)
                    .addComponent(answer2Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer3Btn)
                    .addComponent(answer4Btn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(resetBtn))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQuizActionPerformed
        // TODO add your handling code here:
        new lcPhy().setVisible(true);
    }//GEN-LAST:event_backQuizActionPerformed

    private void homeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeQuizActionPerformed
        // TODO add your handling code here:
        new GUI().setVisible(true);
    }//GEN-LAST:event_homeQuizActionPerformed

    private void bQQ3TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQQ3TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bQQ3TFActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
       
        
       // try{
            
           //  String input1,input2,input3,input4,input5,input6, answer1, answer2, answer3,answer4;
            // input1 = bQQ1TF.getText();
            // input2 = bQQ2TF.getText();
             //input3 = bQQ3TF.getText();
            // input4 = pQQ1TF.getText();
             //input5 = pQQ2TF.getText();
             //input6 = bQQ3TF.getText();
             //answer1 = answer1Btn.getString();
             //answer2 = answer2Btn.getString();
             //answer3 = answer3Btn.getString();
             //answer4 = answer4Btn.getString();
             //bQQ1TF.setText("");
             //bQQ2TF.setText("");
             //bQQ3TF.setText("");
             //pQQ1TF.setText("");
             //pQQ2TF.setText("");
             //pQQ3TF.setText("");
             //answer1Btn.setString(answer);
        
            //File f = new File ("quizinput.txt");
            //FileWriter fw = new FileWriter (f);
           // //BufferedReader bReader = new BufferedReader (fr);
            //BufferedWriter bWriter = new BufferedWriter (fw);
            //bWriter.write(input1);
            //bWriter.write(input2);
            //bWriter.write(input3);
            //bWriter.write(input4);
            //bWriter.write(input5);
            //bWriter.write(input6);
            
            //bWriter.close();
        //} catch (IOException e){
          //  System.out.println(e.toString());
          //  System.out.println("Problem Writing to File");
        //}
        
       // Watch this video https://www.youtube.com/watch?v=L84QSSGLJAs
    }//GEN-LAST:event_submitBtnActionPerformed

    private void answer1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1BtnActionPerformed
        // TODO add your handling code here:
        answer="Answer 1";
    }//GEN-LAST:event_answer1BtnActionPerformed

    private void answer2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2BtnActionPerformed
        // TODO add your handling code here:
        answer="Answer 2";
    }//GEN-LAST:event_answer2BtnActionPerformed

    private void answer3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3BtnActionPerformed
        // TODO add your handling code here:
        answer="Answer 3";
    }//GEN-LAST:event_answer3BtnActionPerformed

    private void answer4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4BtnActionPerformed
        // TODO add your handling code here:
        answer="Answer 4";
    }//GEN-LAST:event_answer4BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PicQueLbl;
    private javax.swing.JRadioButton answer1Btn;
    private javax.swing.JRadioButton answer2Btn;
    private javax.swing.JRadioButton answer3Btn;
    private javax.swing.JRadioButton answer4Btn;
    private javax.swing.JLabel bQQ1Lbl;
    private javax.swing.JTextField bQQ1TF;
    private javax.swing.JLabel bQQ2Lbl;
    private javax.swing.JTextField bQQ2TF;
    private javax.swing.JLabel bQQ3Lbl;
    private javax.swing.JTextField bQQ3TF;
    private javax.swing.JButton backQuiz;
    private javax.swing.JLabel basicQuestionLbl;
    private javax.swing.JButton homeQuiz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mCQ1Lbl;
    private javax.swing.JLabel multipleChoiceLbl;
    private javax.swing.JLabel pQQ1Lbl;
    private javax.swing.JTextField pQQ1TF;
    private javax.swing.JLabel pQQ2Lbl;
    private javax.swing.JTextField pQQ2TF;
    private javax.swing.JLabel pQQ3Lbl;
    private javax.swing.JTextField pQQ3TF;
    private javax.swing.JPanel pic1;
    private javax.swing.JPanel pic2;
    private javax.swing.JPanel pic3;
    private javax.swing.JPanel pic4;
    private javax.swing.JLabel quizLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
    private String answer;
}
